#!/usr/bin/env bash
# Displays information about subdomains

dom="$1"

getdominfo () {
  if [ -z "$2" ]
  then
    subdom=("www" "lb-01" "web-01" "web-02")
  else
    subdom=("$2")
  fi

  for item in "${subdom[@]}"; do
    rec_type=$(dig "$item.$dom" | awk '/ANSWER SECTION:/ { getline; print $4 }')
    dest=$(dig "$item.$dom" | awk '/ANSWER SECTION:/ { getline; print $5 }')
    echo "The subdomain $item is a $rec_type record and points to $dest"
  done
}

getdominfo $1 $2
