#!/usr/bin/env bash
# Transfers a file, some_page.html, from client to server w/ scp.
if [[ $# -eq 4 ]]
then
  eval "$(ssh-agent)"
  ssh-add "$4"
  scp "$1" "$3"@"$2":~/
else
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
