#!/usr/bin/env bash
# Installs nginx web server & serves 'Hello World!'
# when queried at root.

# Update the server.
apt-get update

# Install Nginx and agree to all prompts.
apt-get -y install nginx

# Start Nginx
# service nginx start

# I need to create rules before enabling firewall to avoid denying
# all incoming connections.

# First, allow connections through SSH on port 22.
# ufw allow OpenSSH

# Second, allow connections through http on its port 80.
ufw allow 'Nginx HTTP'

# Enable the firewall.
# ufw enable

# Ensure Nginx has permissions to read & write files in root dir.

# First, assign ownership of html to user running script
# so they have full control over web server files.
chown -R "$USER:$USER" /var/www/html

# Second, set permissions of /var/www & its files to rwx for user,
# r-x for group and others.
chmod -R 755 /var/www

# If index.html already exists in /html, back it up.
# if [[ -f /var/www/html/index.html ]]; then
#  cp /var/www/html/index.html /var/www/html/index.bak
# fi

# Create index.html file with "Hello World!" string
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx without using systemctl.
service nginx start
