#!/usr/bin/env bash
# Configures Nginx server so /redirect_me redirects to another page
# with a permanent redirect.

# Update the server.
apt-get update

# Install Nginx and agree to all prompts.
apt-get -y install nginx

# Start Nginx
service nginx start

# I need to create rules before enabling firewall to avoid denying
# all incoming connections.

# First, allow connections through SSH on port 22.
ufw allow OpenSSH

# Second, allow connections through http on its port 80.
ufw allow 'Nginx HTTP'

# Enable the firewall.
# ufw enable

# Ensure Nginx has permissions to read & write files in root dir.

# First, assign ownership of html to user running script
# so they have full control over web server files.
chown -R "$USER:$USER" /var/www/html

# Second, set permissions of /var/www & its files to rwx for user,
# r-x for group and others.
chmod -R 755 /var/www

# If index.html already exists in /html, back it up.
# if [[ -f /var/www/html/index.html ]]; then
#  cp /var/www/html/index.html /var/www/html/index.bak
# fi

# Create index.html file with "Hello World!" string
echo "Hello World!" > /var/www/html/index.html

# Create replacement string
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/dahunsi-dami permanent;"

# Use sed to do inplace editing of /etc/nginx/sites-enabled/default
sudo sed -i "s#server_name _;#$replacement#" /etc/nginx/sites-enabled/default

# Create the 404.html error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Create replacement string
ereplacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

# Use sed to inplace edit /etc/nginx/sites-enabled/default
sudo sed -i "s#listen 80 default_server;#$ereplacement#" /etc/nginx/sites-enabled/default

# Restart Nginx without using systemctl.
service nginx restart
