#!/usr/bin/env bash
#Pints IP address passed as argument 5 times
#If no argument passed, print this string:
#Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
if [ "$1" ];
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
