#!/usr/bin/env bash
# This script displays a list of all currently running processes.
# shellcheck disable=SC2009
# Requirements: it must:
#
# show all processes, for all users, including those
# +which might not have a TTY
#
# display in a user-oriented format
#
# show process hierarchy
ps -eHo user,pid,%cpu,%mem,vsz,rss,tty,stat,start_time,time,args | grep bash
