#!/usr/bin/env bash
# This  script displays Best School 10 times with an until loop
STR="Best School"
c=1
E="Hi"
while [ $c -le 10 ];
do
	if [ $c -eq 9 ]
	then
		echo "$STR"
		echo "$E"
		((c++))
	else
		echo "$STR"
		((c++))
	fi
done
