#!/usr/bin/env bash
#Gives info about school file as below
#
#Requirements
#Must use if & else (case is forbidden)
#Must check file exists
#If file exists, print given str
#If file doesn't exist, print given str
if [ -e school ];
then
	echo "school file exists"
	
	if [ -s school ];
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f school ];
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
