#!/usr/bin/env bash
#Configures Ubuntu server with given requirements:
#
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8
#Checker for this task is run on Docker

cp /etc/hosts ~/hosts.bak
sed -i 's/^127.0.0.1/127.0.0.2/' ~/hosts.bak
sed -i '$a8.8.8.8\tfacebook.com' ~/hosts.bak
cp -f ~/hosts.bak /etc/hosts
