#!/usr/bin/env bash
#Configures Ubuntu server with given requirements:
#
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8
#Checker for this task is run on Docker

cp /etc/hosts /home/dre/Documents/hosts.bak
sed -i 's/^127.0.0.1/127.0.0.2/' /etc/hosts
sed -i '$a8.8.8.8\tfacebook.com' /etc/hosts
